### ISSUE TITLE
Update API Documentation

### ISSUE THREAD

**Issue by Loubnabambarak** [Deep-Lake-Finance/docs#1]
- [x] generate api docs
- [x] update gitbook & deploy

**Comment by dantrevino** [comment]
Updated API documentation is now available on our current gitbook

**Comment by dantrevino** [comment]
generated api docs from latest branch and deployed to gitbook (live)
https://deep-lake.gitbook.io/deep-lake-instant-btc-liquidity-through-dlcs/developers/deep-lake-bitcoin-api-reference
